name: Automatic Pipeline

on:
  push:
    branches:
      - master

jobs:
  ContinuousIntegration:
    name: Verify integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "20"
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: docker compose -f docker-compose-tests.yml run backend

  PublishDockerImage:
    name: Publish Docker image
    runs-on: ubuntu-latest
    needs: ContinuousIntegration
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/bingo-driven-backend:latest

  ContinuousDeploymentToRender:
    name: Deploy to Render
    runs-on: ubuntu-latest
    needs: PublishDockerImage
    steps:
      - name: Trigger a deploy
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}
